config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'news', to: 'tweets#news'
      get ':date1/:date2', to: 'tweets#date_filter'
      post 'create', to: 'tweets#create'
    end
  end


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users #ruta devise
  delete 'like/:id', to: 'likes#destroy', as:'like_destroy'#ruta para destruir los like
  
  resources :tweets do#ruta anidada para tweets y likes
    resources :likes
  end
  
  get 'home/index'

#ruta anidad para el quote
  resources :users do
    member do
      get 'quote', to: "tweets#quote", as:"quote"
    end
    resources :tweet
  end

  post 'follows/:id', to: 'follows#to_follow', as: 'follow'
  delete 'follows/:id', to: 'follows#to_unfollow', as: 'unfollow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'tweets#index' #root
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :tweets
  paginates_per 50
  #scope :tweets_for_me, -> (user) { where(user_id:  user.followeds.ids)}
  scope :tweets_for_me, -> (user) { where(:user_id => user.followeds.pluck(:followed_id)) } #scope para que muetrrea mis tweets y los de mi amigos

  # Ex:- scope :active, -> {where(:active => true)}
  validates :content, presence: true


#metodo para buscar las imagenes 
  def father_avatar

    Tweet.find(self.tweet_id).user.url_photo

  end

  #metodo para buscar los nombre de las personas que retwittea
  def father_name
    
    Tweet.find(self.tweet_id).user.username
    
  end
  
    def count_tweet
      
      Tweet.where(tweet_id: self.id).count
      
    end
    
end

app/controllers/api/v1/tweets_controller.rb
class Api::V1::TweetsController < ActionController::API  
 
  include ActionController::HttpAuthentication::Basic::ControllerMethods 
  http_basic_authenticate_with name: "fabi", password: "123123", except: :index
  #skip_before_action :verify_authenticity_token

  #cambiar herencia aplicationcontroller
  def news
    #creamos el hash para mostrar los datos en la api
    @tweet = Tweet.includes(:likes)

    #User.includes(:posts)
    api = []
    @tweet.each do |tweet|
      api << Hash[:id => tweet.id, :content => tweet.content, :user_id => tweet.user_id, :likes_count => tweet.likes.count,:retweets_count => tweet.count_tweet,:rewtitted_from => tweet.tweet_id]
    end
    @tweets = api.last(50)#ultimos50 tweets
    render json: @tweets 
  end 

  def date_filter
    #busqueda de tweets segun fechas
    @tweets = Tweet.includes(:likes).where("created_at >= ? AND created_at <= ?", params[:date1].to_date.beginning_of_day, params[:date2].to_date.end_of_day)
    render json: @tweets  
    
  end

  def create
    #creat un tweet para el usuraio id 3 
    @tweets =  User.first.tweet.create(content: params[:content])
    render json: @tweets 

  end
  
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy quote ]
  before_action :authenticate_user!,only: %i[ quote ] #solo usuario authentificado pueden dar rteetear
  

  # GET /tweets or /tweets.json
  def index
    # Buqueda parcial
    if params[:q]
      @tweets = Tweet.where('content LIKE ?', "%#{params[:q]}%").order(created_at: :desc).page params[:page] #este codigo  se para la busqueda parcial
    elsif user_signed_in?
      
      @tweets= Tweet.tweets_for_me(current_user).or(current_user.tweet).order(created_at: :desc).page params[:page]
      
    else
      @tweets= Tweet.eager_load(:user, :likes).order(created_at: :desc).page params[:page]
    end
    @tweet = Tweet.new
    @user_likes = Like.where(user: current_user).pluck(:tweet_id)
    #@users  = User.all cambiar para subir a heroku

  end
  # GET /tweets/1 or /tweets/1.json
  def show
    @tweet_likes = @tweet.likes
  end


  def quote
    @quote = Tweet.new

    @quote.content = @tweet.content # se cargar el  content tweet a quote
    @quote.user_id = current_user.id # se cargar el curren user a la columna user id del quote
    @quote.tweet_id = @tweet.id # se cargar el tweet.id a quote
    @quote.created_at = DateTime.now #se cargar la fecha creacion a quote
    @quote.updated_at = DateTime.now #se cargar la fecha de actualizacion a quote
    respond_to do |format| #se direcciona al root
      if @quote.save
        format.html { redirect_to root_path, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id #se guarda el usuario y el tweet
    respond_to do |format|#redirrecciona al root
      if @tweet.save
        format.html { redirect_to root_path, notice: "Felicitaciones has twitteado" }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html {  redirect_to root_path, notice: "Favor ingresa un Tweet"}
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
    

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end
end

app/helpers/api/v1/tweets_helper.rb
module Api::V1::TweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

    def hashtag(content)
        format_content = content.split(" ")
        tag = []
        format_content.each do |p|
            if p.start_with?("#")
                p = link_to p, controller: 'tweets', q: p
            end
            tag.push(p)
        end
        raw tag.join(" ")
    end
    

end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <% if current_user.url_photo %>
    <div class = "container img_title">
      <%= image_tag current_user.url_photo,:class =>"img-fluid  rounded-circle  border border-primary p-2 " %>
    </div>
 <% end %>
    <%= form.text_area :content, class:"form-control border mt-4 rounded-pill border-primary background-textarea ",placeholder:" ¿Que estas pensando @#{current_user.username}?" %>
  </div>

  <div class="actions my-2">
    <%= form.submit "Twittear", :class => "btn btn-primary text-black rounded-pill mb-3 mt-3 " %>
  </div>

<% end %>

app/views/tweets/_users_to_follow.html.erb
<div class="images-basic">
  <% @current_user.can_follow.each do |user| %>
    <%if current_user != user.id %>
        <%= link_to follow_path(user.id), method: :post do %>
          <%=image_tag user.url_photo %>
        <%end %>
    <%end %>
<% end %>

</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice" class="text-center mr-5 text-muted font-weight-bold"><%= notice %></p>

<% if user_signed_in? %>
    <div class= "container">
        <%= render 'users_to_follow' %>
    </div>
<%end %>



<!-- icono principal -->
<div class="container">
  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-twitter logotwitter " width="60" height="60" viewBox="0 0 24 24" stroke-width="1.5" stroke="#00abfb" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M22 4.01c-1 .49 -1.98 .689 -3 .99c-1.121 -1.265 -2.783 -1.335 -4.38 -.737s-2.643 2.06 -2.62 3.737v1c-3.245 .083 -6.135 -1.395 -8 -4c0 0 -4.182 7.433 4 11c-1.872 1.247 -3.739 2.088 -6 2c3.308 1.803 6.913 2.423 10.034 1.517c3.58 -1.04 6.522 -3.723 7.651 -7.742a13.84 13.84 0 0 0 .497 -3.753c-.002 -.249 1.51 -2.772 1.818 -4.013z" />
  </svg>
</div>
<hr>


<!-- render form tweet -->

<% if user_signed_in? %>
    <div>
        <%= render 'tweets/form', tweet: @tweet %>
    </div>
<%end %>

<!-- codigo para mostrar tarjetas con los contenidos del tweer-->
<% @tweets.each do |tweet| %>


  <% if tweet.tweet_id == nil %>

<!--  Card-->
    <div class="card text-white bg-primary rounded-3 border border-info mb-3" style="max-width: 80rem;">
  <!-- imagen el usuario del monento en las card-->
        <% if tweet.user.url_photo %>
          <%= image_tag tweet.user.url_photo,:class =>"img-fluid rounded-circle img ml-3 mt-3 border border-primary p-1" %>
        <% end %>
      <!-- tiempor del posteo-->
      <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet, class:" text-warning ml-auto mr-2"%>

      <!-- nombre del usuario en la card-->
      <div class="card-header">@<%= tweet.user.username %> dice:</div>
      <div class="card-body">
        <h5 class="card-title"></h5>

        <!-- contenido del post del usario en la card-->
        <p class="card-text"><p class="card-text"><%= hashtag(tweet.content) %></p></p>
        <!-- solo se motrara los siguiente si cliente esta regsitrado-->
        
        <!-- contador de likes-->
          <%= tweet.likes.count %>
          <!-- if para los like-->
            <%if @user_likes.include?(tweet.id) %>
            <!-- sino muestra los like no rotos-->
              <%= link_to like_destroy_path(tweet.id), method: :delete do %> 
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#a905b6" fill="1" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                  </svg>
              <% end %>

            <% else %>
          <!-- sino muestra los like rotos-->
              <%= link_to tweet_likes_path(tweet), method: :post do %> 
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-heart" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#ff2825" fill="1" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                  <path d="M12 7l-2 4l4 3l-2 4v3" />
                </svg>
              <% end %>

            <% end %>


        
            <!-- bonton de rtweet-->
            <%= link_to quote_user_path(tweet.id),:class => 'nav-icon' do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-rotate-rectangle"width="28" height="28" viewBox="0 0 24 24" stroke-width="3" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M16.3 5h.7a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2h5l-2.82 -2.82m0 5.64l2.82 -2.82" transform="rotate(-45 12 12)" />
                </svg>
            <% end %>

  
      </div>
      </div>

  <%else %><!-- fin si nil-->

    <div class="card text-white bg-primary rounded-3 border border-info mb-3" style="max-width: 80rem;">
  <!-- imagen el usuario del monento en las card-->
      <% if tweet.user.url_photo %>
        <%= image_tag tweet.user.url_photo,:class =>"img-fluid rounded-circle img ml-3 mt-3 border border-primary p-1" %>
      <% end %>
      <!-- tiempor del posteo-->
      <%= link_to distance_of_time_in_words(Time.now, tweet.created_at), tweet, class:" text-warning ml-auto mr-2"%>

      <!-- nombre del usuario en la card-->
      <div class="card-header">@<%= tweet.user.username %> retwittea:</div>
      <div class="card-body">
        <h5 class="card-title"></h5>

        <!-- contenido del post del usario en la card-->
        <p class="card-text"><p class="card-text"> <%= image_tag tweet.father_avatar, class:"img-fluid rounded-circle img ml-3 mt-3 border border-primary p-1" %><%=tweet.father_name %> dice:<%= hashtag(tweet.content) %></p></p>
        <!-- solo se motrara los siguiente si cliente esta regsitrado-->
  
        <!-- contador de likes-->
          <%= tweet.likes.count %>
          <!-- if para los like-->
            <%if @user_likes.include?(tweet.id) %>
            <!-- sino muestra los like no rotos-->
              <%= link_to like_destroy_path(tweet.id), method: :delete do %> 
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#a905b6" fill="1" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                  </svg>
              <% end %>

            <% else %>
          <!-- sino muestra los like rotos-->
              <%= link_to tweet_likes_path(tweet), method: :post do %> 
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-heart" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#ff2825" fill="1" stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                  <path d="M12 7l-2 4l4 3l-2 4v3" />
                </svg>
              <% end %>

            <% end %>

          <!-- contador de tweets-->
          <%=tweet.count_tweet%>
            <!-- bonton de rtweet-->
            <%= link_to quote_user_path(tweet.id),:class => 'nav-icon' do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-rotate-rectangle"width="28" height="28" viewBox="0 0 24 24" stroke-width="3" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M16.3 5h.7a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2h5l-2.82 -2.82m0 5.64l2.82 -2.82" transform="rotate(-45 12 12)" />
                </svg>
            <% end %>

    
      </div>
      </div>


  <%end%><!-- fin si nil-->

<%end%><!-- fin each-->


    <% paginate @tweets %>
    


    <%= link_to_previous_page  @tweets, 'Pagina Anterior de Tweets',class:" btn btn-primary rounded-pill  "%>
    <%= link_to_next_page @tweets, 'Motrar Mas  Tweets', class:"btn btn-primary rounded-pill "%>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Inicio', tweets_path,:class => "btn btn-primary text-black rounded-pill mb-3 mt-3 " %>




    <%@tweet_likes.each do |p1|%>
  <div class = "container text-center">
<div class="row">
<div class>
    <div class="col-sm card pt-4 mb-3 " style="width: 18rem;">
  <%=image_tag p1.user.url_photo %>
  <div class="card-body">
    <h5 class="card-title">@<%= p1.user.username%> le gusta este tweet¡¡</h5>
    <p class="card-text"></p>
    <%= link_to 'Back', tweets_path %>
  </div>
</div>
</div>
</div>

</div>
  <%end%>




<%= link_to 'Edit', edit_tweet_path(@tweet) %> 
<%= link_to 'Back', tweets_path %>